version: "3.5"

services:
  client:
    command: nginx -g "daemon off;"
    volumes:
      - /srv/patjcj-staging/images:/usr/share/nginx/html/images:rw
    deploy:
      placement:
        constraints:
          - node.hostname == sys.prforge.com

  server:
    env_file:
      - ./server/docker/staging.env
    environment:
      NODE_ENV: staging
    command: "npm start"
    volumes:
      - /srv/patjcj-staging/images:/tmp/images:rw
    deploy:
      placement:
        constraints:
          - node.hostname == sys.prforge.com
