version: "3.5"

services:
  client:
    volumes:
      - /srv/patjcj/images:/usr/share/nginx/html/images:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: nginx -g "daemon off;"
    deploy:
      placement:
        constraints:
          - node.hostname == sys.prforge.com

  server:
    volumes:
      - /srv/patjcj/images:/tmp/images:rw
    env_file:
      - ./server/docker/production.env
    environment:
      NODE_ENV: production
    command: "npm start"
    deploy:
      placement:
        constraints:
          - node.hostname == sys.prforge.com
