version: "3.5"

networks:
  traefik-public:
    external: true
  patjcj-production:
    external: false
  patjcj-staging:
    external: false

services:
  client:
    volumes:
      - /tmp/images:/data/public/images:rw
    command: npm run serve
    build: 
      context: ./client      
      target: builder
    ports:
      - 8080:8080

  server:
    volumes:
      - /tmp/images:/tmp/images:rw
    command: npm run start:dev

    build: 
      context: ./server      
      target: builder
    env_file:
      - ./server/docker/dev.env 
